# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(related_name='in_wishlist', to='login_reg.User'),
        ),
    ]
