# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='in_wishlist', to='login_reg.User'),
        ),
    ]
