# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('items', '0003_auto_20170127_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='login_reg.User'),
        ),
    ]
