# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('items', '0004_item_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='item',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='in_favorites', to='login_reg.User'),
        ),
    ]
